# Generated by Django 4.1 on 2023-06-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_userinfo_delete_movie"),
    ]


    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField()),
                ("genre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField()),
                ("keyword", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField()),
                ("title", models.CharField( max_length=100)),
                ("overview", models.TextField()),
                ("poster_path", models.URLField( max_length=255, null=True )),
                ("year", models.IntegerField()),
                ("vote_average", models.FloatField()),
                ("keywords", models.ManyToManyField(to="api.keyword")),
                ("genres", models.ManyToManyField(to="api.genre")),
                ("trailer_link", models.URLField( max_length=255, null=True )),
            ],
        ),
    ]
