# Generated by Django 4.1 on 2023-06-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_genre_keyword_remove_movie_release_date_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="movie", table="api_movie",),
    ]
